# Generated by Django 3.1.7 on 2021-03-10 20:52

import datetime
from django.conf import settings
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('student_number', models.IntegerField(primary_key=True, serialize=False)),
                ('user_rank', models.CharField(choices=[('rookie', 'ROOKIE'), ('lieutenant', 'LIEUTENANT'), ('captain', 'CAPTAIN'), ('colonel', 'COLONEL'), ('general', 'GENERAL')], default='Rookie', max_length=10)),
                ('astro_credits', models.IntegerField(default=0)),
                ('daily_tasks', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), default=list, size=3)),
                ('weekly_credits', models.IntegerField(default=0)),
                ('weekly_reset_date', models.DateField(default=datetime.datetime(2021, 3, 17, 0, 0))),
                ('daily_reset_date', models.DateField(default=datetime.datetime(2021, 3, 11, 0, 0))),
                ('favourite_module_name', models.CharField(default='n/a', max_length=200)),
                ('personal_goals', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=250), default=list, size=10)),
                ('first_login', models.BooleanField(default=True)),
                ('rank_badge', models.ImageField(default='assets/rank1.svg', upload_to='')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StaffProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_login', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
